#!/bin/sh

if ! grep -qw "ts-silo=1" /proc/cmdline 2>&1; then
	# Supercaps are not present or turned off
	exit 1
fi

MODEL=$(strings /proc/device-tree/model | tr ' ' '\n' | grep TS-)

if [ "$MODEL" != "TS-7990" ]; then
	echo "Supercaps not supported on $MODEL"
	exit 0
fi

# This is extremely conservative, but allows running off
# of caps for ~10-15 seconds
RESET_PCT=90

# Pin 7 of the DIO header will go high if VIN is removed.
# We can poll the FPGA pin (GPIO 249), but the CPU GPIO supports interrupts.
# Change the FPGA crossbar so FPGA_IRQ_1 outputs the value on DIO_6
export FPGA_IRQ_1=DIO_6
tshwctl --set

# POWER_FAIL is:
GPIOCHIP="209c000.gpio"
GPIOLINE="4"

# Check if the GPIO line is valid
if ! gpioget $GPIOCHIP $GPIOLINE >/dev/null 2>&1; then
	echo "Failed to get GPIO line $GPIOLINE on chip $GPIOCHIP"
	exit 1
fi

# while POWER_FAIL is high, check supercap levels
while true ; do
	# Read the GPIO line (this will set $gpio_value to 0 or 1)
	gpio_value=$(gpioget $GPIOCHIP $GPIOLINE)

	if [ "$gpio_value" -ne 1 ]; then
		sleep .5
		continue
	fi

	# Read the supercap percentage
	eval "$(tsmicroctl -i)" # sets $SUPERCAP_PCT
	echo "Supercaps at ${SUPERCAP_PCT}"

	if [ "${SUPERCAP_PCT}" -le ${RESET_PCT} ]; then
		wall "The script tssilomon has detected main power has been lost! Shutting down safely to prevent filesystem damage."
		reboot
		exit
	fi

	sleep 0.5
done